sonar.projectKey=mduran-bot_proyecto_cenco_replica
sonar.organization=mduran-bot

# 1. FUENTES: Solo la carpeta con la lógica de negocio
sonar.sources=max/polling/src

# 2. TESTS: Solo la carpeta de tests o el archivo específico
# Si tus tests están en una carpeta llamada 'tests' dentro de polling:
sonar.tests=max/polling/tests
# O si están sueltos en polling, asegúrate de que 'src' no esté contenido aquí
# sonar.tests=max/polling/nombre_de_tu_carpeta_de_tests

# 3. REPORTES
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=nosetests.xml

# 4. EXCLUSIONES: Importante para evitar conflictos
sonar.exclusions=**/*.md, **/*.env, **/docs/**, **/terraform/**, **/spec/**, **/examples/**