# Identificadores únicos (Cópialos exactos de tu panel de SonarCloud)
sonar.projectKey=mduran-bot_proyecto_cenco_replica
sonar.organization=mduran-bot

# Configuración de los reportes generados en el paso anterior
# Le decimos a Sonar: "Lee este XML para saber qué líneas probé"
sonar.python.coverage.reportPaths=coverage.xml
# Y este para saber cuántos tests fallaron:
sonar.python.xunit.reportPath=nosetests.xml

# Organización del análisis
sonar.sources=.       # Analiza todo el código en la raíz
sonar.tests=max/polling/     # Indica dónde están tus archivos de prueba (carpeta tests)
sonar.exclusions=**/venv/**, **/tests/** # No analices la librería de Python ni los propios tests como si fueran código fuente