name: SonarQube Cloud Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: Test & Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov requests pandas jsonschema hypothesis pyspark boto3 apache-airflow
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test with pytest and generate coverage
        env:
          # Mantenemos el PYTHONPATH para que encuentre 'src' y 'api_client'
          PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/max/polling:${{ github.workspace }}/max/polling/src
        run: |
          # Ejecutamos SOLO el archivo deseado
          pytest max/polling/test_localstack_with_real_api.py --cov=max/polling/src --cov-report=xml:coverage.xml --junitxml=nosetests.xml
        continue-on-error: true 

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}